# Generated by Django 5.2 on 2025-05-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arma', models.CharField(max_length=20)),
                ('skin_pack', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
