# Generated by Django 5.2 on 2025-05-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_skin_delete_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='fecha_de_agrego',
            field=models.DateField(null=True),
        ),
    ]
